server:
  port: 8761      # 端口号

eureka:
  instance:
    hostname: localhost   # localhost
  client:
    # 当前的eureka服务是单机版的
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://root:root@localhost:8761/eureka
# 指定用户名和密码
spring:
  security:
    user:
      name: root
      password: root
  application:
    name: EUREKA